Repository swissfintechinnovations/ca-mortgage, pull requests merged in 2022-11, with the labels that each got.

#107 Change details for commonErrorResponse
  mortgageAPI.yaml
Labels: enhancement

#89 Inconsistency in Duration
  mortgageAPI.yaml
Labels: enhancement

#99 Renaming Estimation Amount in Release V3.0
  mortgageAPI.yaml
Labels: enhancement

#105 Required Fields in Liabilities and Income
  mortgageAPI.yaml
Labels: enhancement

#110 Add standard response 201
  mortgageAPI.yaml
Labels: enhancement

#97 Assets and UsedAssets
  mortgageAPI.yaml
Labels: documentation

#117 New Enum in Asset Type
  mortgageAPI.yaml
Labels: enhancement

#100 Renaming increment in V3.0
  mortgageAPI.yaml
Labels: enhancement

#96 New Endpoint for full data transfer
  mortgageAPI.yaml
Labels: enhancement

#98 Grammar mistake in Other Features in V3.0
  mortgageAPI.yaml
Labels: bug

#91 Additional step for getting binding offers
  mortgageAPI.yaml
Labels: enhancement

#114 Energy certificate from Cantons
  mortgageAPI.yaml
Labels: enhancement

#112 Fix for Name and Surname examples
  mortgageAPI.yaml
Labels: enhancement

#122 Fix Rls 3.0.0
  mortgageAPI.yaml
Labels: bug
